apiVersion: v1
kind: Service
metadata:
  name: aismb-interface-service
  namespace: aismb-health
  labels:
    app: aismb-interface
spec:
  type: LoadBalancer
  selector:
    app: aismb-interface
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
