apiVersion: v1
kind: Service
metadata:
  name: aismb-whatsapp-service
  namespace: aismb-health
  labels:
    app: aismb-whatsapp
spec:
  type: LoadBalancer
  selector:
    app: aismb-whatsapp
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
